[package]
name = "woke"
version = "0.0.1"
authors = ["Richard Anaya"]
edition = "2018"
description = "A minimalistic waker implementation for executors"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
