[package]
name = "single_task_executor"
version = "0.1.0"
authors = ["richard <richard>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
woke = { path = "../../" }
once_cell = "1.2.0"